# Generated by Django 6.0.5 on 2026-06-06 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('items', models.TextField()),
                ('quantity', models.IntegerField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='Open', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('delivery_timeline', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.rfq')),
            ],
        ),
    ]
